version: '3'

services:
  db:
    image: postgres:11
    restart: always
    container_name: workshopDB
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: idris
      POSTGRES_PASSWORD: idrisaja
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  workshop:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
   # depends_on:
   #   - db
  webserver:
    image: nginx:latest
    container_name: web_server01
    ports:
      - "80:80"
